sonar.projectKey=instagram-devops-project
sonar.projectName=instagram-devops-project
sonar.projectVersion=1.0

sonar.sources=.
sonar.host.url=http://192.168.0.50:9000
sonar.login=squ_dfb6003d0dfb32568aa6bbac4f1e1f97963949b6
